version: 1

builds:
  - id: gora
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/gora
    binary: gora

  - id: gorad
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./cmd/gorad
    binary: gorad


archives:
  - format: tar.gz
    # This name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

dockers:
  - image_templates:
      - "ghcr.io/yutarohayakawa/gorad:{{ .Tag }}"
      - "ghcr.io/yutarohayakawa/gorad:latest"
