// generated by deep-copy -pointer-receiver --type Config --type InterfaceConfig -o zz_generated_deepcopy.go .; DO NOT EDIT.

package radv

// DeepCopy generates a deep copy of *Config
func (o *Config) DeepCopy() *Config {
	var cp Config = *o
	if o.Interfaces != nil {
		cp.Interfaces = make([]*InterfaceConfig, len(o.Interfaces))
		copy(cp.Interfaces, o.Interfaces)
		for i2 := range o.Interfaces {
			if o.Interfaces[i2] != nil {
				cp.Interfaces[i2] = o.Interfaces[i2].DeepCopy()
			}
		}
	}
	return &cp
}

// DeepCopy generates a deep copy of *InterfaceConfig
func (o *InterfaceConfig) DeepCopy() *InterfaceConfig {
	var cp InterfaceConfig = *o
	return &cp
}
