// Code generated by deepcopy-gen Config Status InterfaceConfig InterfaceStatus; DO NOT EDIT.

package ra

// deepCopy generates a deep copy of *Config
func (o *Config) deepCopy() *Config {
	var cp Config = *o
	if o.Interfaces != nil {
		cp.Interfaces = make([]*InterfaceConfig, len(o.Interfaces))
		copy(cp.Interfaces, o.Interfaces)
		for i2 := range o.Interfaces {
			if o.Interfaces[i2] != nil {
				cp.Interfaces[i2] = o.Interfaces[i2].deepCopy()
			}
		}
	}
	return &cp
}

// deepCopy generates a deep copy of *Status
func (o *Status) deepCopy() *Status {
	var cp Status = *o
	if o.Interfaces != nil {
		cp.Interfaces = make([]*InterfaceStatus, len(o.Interfaces))
		copy(cp.Interfaces, o.Interfaces)
		for i2 := range o.Interfaces {
			if o.Interfaces[i2] != nil {
				cp.Interfaces[i2] = o.Interfaces[i2].deepCopy()
			}
		}
	}
	return &cp
}

// deepCopy generates a deep copy of *InterfaceConfig
func (o *InterfaceConfig) deepCopy() *InterfaceConfig {
	var cp InterfaceConfig = *o
	return &cp
}

// deepCopy generates a deep copy of *InterfaceStatus
func (o *InterfaceStatus) deepCopy() *InterfaceStatus {
	var cp InterfaceStatus = *o
	return &cp
}
