name: Check Codegen

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ./go.mod

    - name: Check deepcopy
      run: make check-deepcopy
