name: Tests

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ./go.mod

    - name: Run unit tests
      run: go test -v

    - name: Run integration tests
      run: go test -exec "sudo -E" -v ./integration_tests
